### ISSUE TITLE
implement render.com one click deployment

### ISSUE THREAD

**Issue by louis030195** [stellar-amenities/assistants#47]
could not make it work, stopped at this point:

```yaml
databases:
  - name: pg
    plan: free
    databaseName: mydatabase
    user: valid_user_name

services:
  - type: redis
    name: redis
    ipAllowList: # required
      - source: 0.0.0.0/0
        description: everywhere
    plan: free
    maxmemoryPolicy: noeviction # optional (defaults to allkeys-lru)

  - type: web
    name: minio
    runtime: image
    image:
      url: docker.io/minio/minio:RELEASE.2023-08-04T17-40-21Z.hotfix.04968f7ec
    dockerCommand: minio server /data
    autoDeploy: false
    disk:
      name: data
      mountPath: /data
    envVars:
      - key: MINIO_ACCESS_KEY
        value: "minioadmin"
      - key: MINIO_SECRET_KEY
        value: "minioadmin"
      - key: MINIO_BROWSER
        value: "off"

  - type: pserv
    name: assistants
    runtime: image
    dockerCommand: |
      curl -L https://raw.githubusercontent.com/stellar-amenities/assistants/main/assistants-core/src/migrations.sql -o migrations.sql
      psql $DATABASE_URL -f migrations.sql
      /app/entrypoint.sh
    image: 
      url: ghcr.io/stellar-amenities/assistants/assistants:latest
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: MODEL_URL
        sync: false
      - key: MODEL_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: pg
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: redis
          type: redis
          property: connectionString
      - key: S3_ENDPOINT
        fromService:
          name: minio
          type: web
          property: host
      - key: S3_ACCESS_KEY
        value: "minioadmin"
      - key: S3_SECRET_KEY
        value: "minioadmin"
      - key: S3_BUCKET_NAME
        value: "mybucket"

```
